### ISSUE TITLE
WP8.1 WinRT exception at WebDavSession.ListAsync

### ISSUE THREAD

**Issue by jp-weber** [DecaTec/Portable-WebDAV-Library#64]
The exceptions occurs when WebDavSession.ListAsync is executed.
```
An exception of type 'System.NotSupportedException' occurred in mscorlib.ni.dll but was not handled in user code. Additional information: Specified method is not supported.
```

Stacktrace
```
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DecaTec.WebDav.WebDavClient.<SendAsync>d__187.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DecaTec.WebDav.WebDavSession.<ListAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NextcloudClient.NextcloudClient.<List>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NextcloudApp.Services.DirectoryService.<StartDirectoryListing>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NextcloudApp.Services.DirectoryService.<StartDirectoryListing>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NextcloudApp.ViewModels.DirectoryListPageViewModel.<StartDirectoryListing>d__125.MoveNext()
```

**Comment by DecaTec** [comment]
Seems to be a problem with WP 8.1 and `System.Net.Http.HttpClient`. Could you try to use a `System.Net.Http.HttpClient` directly in your WP 8.1 app? Does it work?

Since version 0.7, the library is based in .NET standard 1.1 and uses `System.Net.Http.HttpClient`.
Earlier versions contained an UWP part which uses `Windows.Web.Http.HttpClient`. This should also work for WP 8.1: https://github.com/DecaTec/Portable-WebDAV-Library/releases/tag/v0.6.3.0

Anyway, WP 8.1 has reached EOL in 2017.

**Comment by jp-weber** [comment]
Thank you for the fast response.

I haven't had any problems here yet with System.Net.Http and .Net standard, especially because WP8.1 supports version 1.2 of .Net standard. The short test with System.Net.HTTP earlier didn't show any problems either. I will try to add and debug the project directly tonight and then try version 0.6.3 as well.

The project based on WP8.1 is for me only a hobby😃

**Comment by DecaTec** [comment]
You could also try to use the class `WebDavClient` directly. Also great would be a little code example or even the exact point in the code where the exception is thrown (just clone the Portable WebDAV Library).

Have you experienced any problems when using Windows 10 Mobile? When not, I'm afraid that this is a WP 8.1 specific problem.

**Comment by jp-weber** [comment]
I have downloaded the project and compile the project as debug. So I could follow all the steps one by one and have determined that the problem is based on the initialization of WebDavClient with the `HttpVersion 2.0`. With `HttpVersion 1.1` it works perfect.

PS: My app is based on https://github.com/nextcloud/windows-universal

Strangely enough I haven't found any documentation from MS about it, that there are limits here.

**Comment by DecaTec** [comment]
OK, seems that WP 8.1 cannot handle HTTP/2.
Anyway, thank you for the investigation!
